architect:
- tmoreira2020
assets:
  pubring.gpg: tmoreira2020/home#assets/pubring.gpg
  secring.gpg: tmoreira2020/home#assets/secring.gpg
  settings.xml: tmoreira2020/home#assets/settings.xml
merge:
  script: |-
    mvn clean install --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
deploy:
  script: |-
    mvn clean deploy --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    sed "s/>[0-9].[0-9].[0-9]</>${tag}</g" README.md > README.md.releaseBackup
    cp README.md.releaseBackup README.md
    sed "s/\"[0-9].[0-9].[0-9]\"/\"${tag}\"/g" README.md > README.md.releaseBackup
    cp README.md.releaseBackup README.md
    git commit -am "${tag}"
    mvn clean deploy -Psonatype-oss-release --errors --settings ../settings.xml
    git checkout master
    git merge __rultor
    git checkout -b develop
    mvn build-helper:parse-version versions:set -DnewVersion=$\{parsedVersion.majorVersion\}.$\{parsedVersion.minorVersion\}.$\{parsedVersion.nextIncrementalVersion\}-SNAPSHOT
    git commit -am "Prepare for next development iteration"
    git checkout master
  commanders:
  - tmoreira2020
